name: reviewdog(textlint)
on: [pull_request]
jobs:
  textlint1:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check fix/failonerror no settings
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          textlint_flags: "doc/**"

  textlint2:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review fix/failonerror no settings
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "doc/**"

  textlint3:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check fix/failonerror fail_on_error
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          textlint_flags: "doc/**"

  textlint4:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review fix/failonerror fail_on_error
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          textlint_flags: "doc/**"

  textlint5:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check fix/failonerror fail_level
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_level: warning
          textlint_flags: "doc/**"

  textlint6:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review fix/failonerror fail_level
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: warning
          textlint_flags: "doc/**"

  textlint7:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check fix/failonerror fail_on_error and fail_level
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          fail_level: warning
          textlint_flags: "doc/**"

  textlint8:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-pr-review fix/failonerror fail_on_error and fail_level
        uses: tsuyoshicho/action-textlint@fix/failonerror
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          fail_level: warning
          textlint_flags: "doc/**"
