name: reviewdog
on: [pull_request]
jobs:
  vimlint:
    name: runner / vimlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: vimlint-github-check
        uses: tsuyoshicho/action-vimlint@feature/opt-update
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          target: testdata
      - name: vimlint-pr-review
        uses: tsuyoshicho/action-vimlint@feature/opt-update
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          target: testdata
